FLASK_APP=manage.py
#设置flask运行环境为development
FLASK_ENV=development

MAIL_SERVER=smtp.163.com
MAIL_PORT=25
MAIL_USE_TLS=True
MAIL_USE_SSL=False
MAIL_USERNAME=liefengwind@163.com
MAIL_PASSWORD=VYLMOFRBMZHAVWHT